### ISSUE TITLE
Review phrases

### ISSUE THREAD

**Issue by vbezruchkin** [intelliants/subrion-template-cars#1]
It looks like we have some of them in our default core installation. Template version should be 1.0.0 or 4.0.0 You decide.

**Comment by nextlayers** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/14039748/10712681/a74e2ae6-7aa1-11e5-99f3-488cb6f15a78.jpg)

Thats the message I got when I tried uploading!!!

**Comment by 4unkur** [comment]
Hello @nextlayers,

Please, rename the folder "subrion-template-cars-master" to just "cars"

**Comment by vbezruchkin** [comment]
And it's not officially released. It can only be used with the core version 4.0 and new autos version that will be released next week.

Cheers

**Comment by nextlayers** [comment]
Min Core Version: 4.0 Incompatible!!! Is there a place to view the demo online? @4unkur thanks!!! it works!!!

**Comment by nextlayers** [comment]
Okay! thanks for getting in touch
